# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/phisco/.local/share/JetBrains/Toolbox/apps/CLion/ch-0/181.5087.36/bin/cmake/bin/cmake

# The command to remove a file.
RM = /home/phisco/.local/share/JetBrains/Toolbox/apps/CLion/ch-0/181.5087.36/bin/cmake/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/phisco/github/advanced_algorithms_project

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/phisco/github/advanced_algorithms_project

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/home/phisco/.local/share/JetBrains/Toolbox/apps/CLion/ch-0/181.5087.36/bin/cmake/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/home/phisco/.local/share/JetBrains/Toolbox/apps/CLion/ch-0/181.5087.36/bin/cmake/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/phisco/github/advanced_algorithms_project/CMakeFiles /home/phisco/github/advanced_algorithms_project/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/phisco/github/advanced_algorithms_project/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named pearce_nr

# Build rule for target.
pearce_nr: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 pearce_nr
.PHONY : pearce_nr

# fast build rule for target.
pearce_nr/fast:
	$(MAKE) -f CMakeFiles/pearce_nr.dir/build.make CMakeFiles/pearce_nr.dir/build
.PHONY : pearce_nr/fast

#=============================================================================
# Target rules for targets named nuutila

# Build rule for target.
nuutila: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 nuutila
.PHONY : nuutila

# fast build rule for target.
nuutila/fast:
	$(MAKE) -f CMakeFiles/nuutila.dir/build.make CMakeFiles/nuutila.dir/build
.PHONY : nuutila/fast

#=============================================================================
# Target rules for targets named main

# Build rule for target.
main: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 main
.PHONY : main

# fast build rule for target.
main/fast:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/build
.PHONY : main/fast

#=============================================================================
# Target rules for targets named transitive_closure

# Build rule for target.
transitive_closure: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 transitive_closure
.PHONY : transitive_closure

# fast build rule for target.
transitive_closure/fast:
	$(MAKE) -f CMakeFiles/transitive_closure.dir/build.make CMakeFiles/transitive_closure.dir/build
.PHONY : transitive_closure/fast

#=============================================================================
# Target rules for targets named pearce

# Build rule for target.
pearce: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 pearce
.PHONY : pearce

# fast build rule for target.
pearce/fast:
	$(MAKE) -f CMakeFiles/pearce.dir/build.make CMakeFiles/pearce.dir/build
.PHONY : pearce/fast

#=============================================================================
# Target rules for targets named test_stdin

# Build rule for target.
test_stdin: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_stdin
.PHONY : test_stdin

# fast build rule for target.
test_stdin/fast:
	$(MAKE) -f CMakeFiles/test_stdin.dir/build.make CMakeFiles/test_stdin.dir/build
.PHONY : test_stdin/fast

#=============================================================================
# Target rules for targets named generate_graph

# Build rule for target.
generate_graph: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 generate_graph
.PHONY : generate_graph

# fast build rule for target.
generate_graph/fast:
	$(MAKE) -f CMakeFiles/generate_graph.dir/build.make CMakeFiles/generate_graph.dir/build
.PHONY : generate_graph/fast

#=============================================================================
# Target rules for targets named tarjan

# Build rule for target.
tarjan: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tarjan
.PHONY : tarjan

# fast build rule for target.
tarjan/fast:
	$(MAKE) -f CMakeFiles/tarjan.dir/build.make CMakeFiles/tarjan.dir/build
.PHONY : tarjan/fast

generate_graph.o: generate_graph.cpp.o

.PHONY : generate_graph.o

# target to build an object file
generate_graph.cpp.o:
	$(MAKE) -f CMakeFiles/generate_graph.dir/build.make CMakeFiles/generate_graph.dir/generate_graph.cpp.o
.PHONY : generate_graph.cpp.o

generate_graph.i: generate_graph.cpp.i

.PHONY : generate_graph.i

# target to preprocess a source file
generate_graph.cpp.i:
	$(MAKE) -f CMakeFiles/generate_graph.dir/build.make CMakeFiles/generate_graph.dir/generate_graph.cpp.i
.PHONY : generate_graph.cpp.i

generate_graph.s: generate_graph.cpp.s

.PHONY : generate_graph.s

# target to generate assembly for a file
generate_graph.cpp.s:
	$(MAKE) -f CMakeFiles/generate_graph.dir/build.make CMakeFiles/generate_graph.dir/generate_graph.cpp.s
.PHONY : generate_graph.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/main.cpp.s
.PHONY : main.cpp.s

main_nuutila.o: main_nuutila.cpp.o

.PHONY : main_nuutila.o

# target to build an object file
main_nuutila.cpp.o:
	$(MAKE) -f CMakeFiles/nuutila.dir/build.make CMakeFiles/nuutila.dir/main_nuutila.cpp.o
.PHONY : main_nuutila.cpp.o

main_nuutila.i: main_nuutila.cpp.i

.PHONY : main_nuutila.i

# target to preprocess a source file
main_nuutila.cpp.i:
	$(MAKE) -f CMakeFiles/nuutila.dir/build.make CMakeFiles/nuutila.dir/main_nuutila.cpp.i
.PHONY : main_nuutila.cpp.i

main_nuutila.s: main_nuutila.cpp.s

.PHONY : main_nuutila.s

# target to generate assembly for a file
main_nuutila.cpp.s:
	$(MAKE) -f CMakeFiles/nuutila.dir/build.make CMakeFiles/nuutila.dir/main_nuutila.cpp.s
.PHONY : main_nuutila.cpp.s

main_pearce.o: main_pearce.cpp.o

.PHONY : main_pearce.o

# target to build an object file
main_pearce.cpp.o:
	$(MAKE) -f CMakeFiles/pearce.dir/build.make CMakeFiles/pearce.dir/main_pearce.cpp.o
.PHONY : main_pearce.cpp.o

main_pearce.i: main_pearce.cpp.i

.PHONY : main_pearce.i

# target to preprocess a source file
main_pearce.cpp.i:
	$(MAKE) -f CMakeFiles/pearce.dir/build.make CMakeFiles/pearce.dir/main_pearce.cpp.i
.PHONY : main_pearce.cpp.i

main_pearce.s: main_pearce.cpp.s

.PHONY : main_pearce.s

# target to generate assembly for a file
main_pearce.cpp.s:
	$(MAKE) -f CMakeFiles/pearce.dir/build.make CMakeFiles/pearce.dir/main_pearce.cpp.s
.PHONY : main_pearce.cpp.s

main_pearce_not_recursive.o: main_pearce_not_recursive.cpp.o

.PHONY : main_pearce_not_recursive.o

# target to build an object file
main_pearce_not_recursive.cpp.o:
	$(MAKE) -f CMakeFiles/pearce_nr.dir/build.make CMakeFiles/pearce_nr.dir/main_pearce_not_recursive.cpp.o
.PHONY : main_pearce_not_recursive.cpp.o

main_pearce_not_recursive.i: main_pearce_not_recursive.cpp.i

.PHONY : main_pearce_not_recursive.i

# target to preprocess a source file
main_pearce_not_recursive.cpp.i:
	$(MAKE) -f CMakeFiles/pearce_nr.dir/build.make CMakeFiles/pearce_nr.dir/main_pearce_not_recursive.cpp.i
.PHONY : main_pearce_not_recursive.cpp.i

main_pearce_not_recursive.s: main_pearce_not_recursive.cpp.s

.PHONY : main_pearce_not_recursive.s

# target to generate assembly for a file
main_pearce_not_recursive.cpp.s:
	$(MAKE) -f CMakeFiles/pearce_nr.dir/build.make CMakeFiles/pearce_nr.dir/main_pearce_not_recursive.cpp.s
.PHONY : main_pearce_not_recursive.cpp.s

main_tarjan.o: main_tarjan.cpp.o

.PHONY : main_tarjan.o

# target to build an object file
main_tarjan.cpp.o:
	$(MAKE) -f CMakeFiles/tarjan.dir/build.make CMakeFiles/tarjan.dir/main_tarjan.cpp.o
.PHONY : main_tarjan.cpp.o

main_tarjan.i: main_tarjan.cpp.i

.PHONY : main_tarjan.i

# target to preprocess a source file
main_tarjan.cpp.i:
	$(MAKE) -f CMakeFiles/tarjan.dir/build.make CMakeFiles/tarjan.dir/main_tarjan.cpp.i
.PHONY : main_tarjan.cpp.i

main_tarjan.s: main_tarjan.cpp.s

.PHONY : main_tarjan.s

# target to generate assembly for a file
main_tarjan.cpp.s:
	$(MAKE) -f CMakeFiles/tarjan.dir/build.make CMakeFiles/tarjan.dir/main_tarjan.cpp.s
.PHONY : main_tarjan.cpp.s

main_transitive_closure.o: main_transitive_closure.cpp.o

.PHONY : main_transitive_closure.o

# target to build an object file
main_transitive_closure.cpp.o:
	$(MAKE) -f CMakeFiles/transitive_closure.dir/build.make CMakeFiles/transitive_closure.dir/main_transitive_closure.cpp.o
.PHONY : main_transitive_closure.cpp.o

main_transitive_closure.i: main_transitive_closure.cpp.i

.PHONY : main_transitive_closure.i

# target to preprocess a source file
main_transitive_closure.cpp.i:
	$(MAKE) -f CMakeFiles/transitive_closure.dir/build.make CMakeFiles/transitive_closure.dir/main_transitive_closure.cpp.i
.PHONY : main_transitive_closure.cpp.i

main_transitive_closure.s: main_transitive_closure.cpp.s

.PHONY : main_transitive_closure.s

# target to generate assembly for a file
main_transitive_closure.cpp.s:
	$(MAKE) -f CMakeFiles/transitive_closure.dir/build.make CMakeFiles/transitive_closure.dir/main_transitive_closure.cpp.s
.PHONY : main_transitive_closure.cpp.s

test_from_stdin.o: test_from_stdin.cpp.o

.PHONY : test_from_stdin.o

# target to build an object file
test_from_stdin.cpp.o:
	$(MAKE) -f CMakeFiles/test_stdin.dir/build.make CMakeFiles/test_stdin.dir/test_from_stdin.cpp.o
.PHONY : test_from_stdin.cpp.o

test_from_stdin.i: test_from_stdin.cpp.i

.PHONY : test_from_stdin.i

# target to preprocess a source file
test_from_stdin.cpp.i:
	$(MAKE) -f CMakeFiles/test_stdin.dir/build.make CMakeFiles/test_stdin.dir/test_from_stdin.cpp.i
.PHONY : test_from_stdin.cpp.i

test_from_stdin.s: test_from_stdin.cpp.s

.PHONY : test_from_stdin.s

# target to generate assembly for a file
test_from_stdin.cpp.s:
	$(MAKE) -f CMakeFiles/test_stdin.dir/build.make CMakeFiles/test_stdin.dir/test_from_stdin.cpp.s
.PHONY : test_from_stdin.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... pearce_nr"
	@echo "... nuutila"
	@echo "... main"
	@echo "... transitive_closure"
	@echo "... pearce"
	@echo "... test_stdin"
	@echo "... rebuild_cache"
	@echo "... generate_graph"
	@echo "... tarjan"
	@echo "... generate_graph.o"
	@echo "... generate_graph.i"
	@echo "... generate_graph.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... main_nuutila.o"
	@echo "... main_nuutila.i"
	@echo "... main_nuutila.s"
	@echo "... main_pearce.o"
	@echo "... main_pearce.i"
	@echo "... main_pearce.s"
	@echo "... main_pearce_not_recursive.o"
	@echo "... main_pearce_not_recursive.i"
	@echo "... main_pearce_not_recursive.s"
	@echo "... main_tarjan.o"
	@echo "... main_tarjan.i"
	@echo "... main_tarjan.s"
	@echo "... main_transitive_closure.o"
	@echo "... main_transitive_closure.i"
	@echo "... main_transitive_closure.s"
	@echo "... test_from_stdin.o"
	@echo "... test_from_stdin.i"
	@echo "... test_from_stdin.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

